<?php
/*
 * PHP is a popular general-purpose scripting language that is especially suited to web development.
 * It is fast, flexible, and pragmatic, powering everything from blogs to the most popular websites.
 */
$page_title = "PHP Fruits Example";
$fruits = ["Apple", "Banana", "Cherry", "Date", "Elderberry"];

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $page_title; ?></title>
    <style>
        body { font-family: sans-serif; background-color: #f0f2f5; }
        .container { max-width: 500px; margin: 40px auto; padding: 20px; background: #fff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        h1 { color: #4B4F56; }
        ul { list-style-type: none; padding: 0; }
        li { background: #e9ebee; margin-bottom: 5px; padding: 10px; border-radius: 4px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>My Favorite Fruits</h1>
        <p>This list is dynamically generated by a PHP script.</p>
        <ul>
            <?php foreach ($fruits as $fruit): ?>
                <li><?php echo htmlspecialchars($fruit); ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
</body>
</html>